# Generated by Django 3.1.7 on 2021-03-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен firebase'),
        ),
    ]
