# Generated by Django 3.1.5 on 2021-02-03 20:59

from django.db import migrations, models
import virtual_day.utils.image_utils
import virtual_day.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210204_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('de', 'German'), ('kk', 'Kazakh')], default='ru', max_length=32, verbose_name='Выбранный язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=virtual_day.utils.image_utils.avatar_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=255, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_changed_datetime',
            field=models.DateTimeField(editable=False, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, unique=True, validators=[virtual_day.utils.validators.validate_phone_number], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'STUDENT'), (1, 'ADMIN')], default=0, verbose_name='Роль'),
        ),
    ]
