# Generated by Django 3.1.7 on 2021-04-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210328_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpushnotification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='userpushnotification',
            name='description_detail',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Текст детального сообщения'),
        ),
    ]
