# Generated by Django 3.1.7 on 2021-03-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_firebase_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru-RU', 'Russian (Russia)'), ('ru', 'Russian'), ('en', 'English'), ('kk', 'Kazakh'), ('de', 'German')], default='ru', max_length=32, verbose_name='Выбранный язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'STUDENT'), (1, 'ADMIN'), (2, 'MODERATOR')], default=0, verbose_name='Роль'),
        ),
    ]
