# Generated by Django 3.1.7 on 2021-04-03 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210403_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpushnotification',
            name='user',
        ),
    ]
