# Generated by Django 3.1.5 on 2021-02-05 16:42

from django.db import migrations, models
import virtual_day.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210204_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[virtual_day.utils.validators.validate_phone_number], verbose_name='Телефон'),
        ),
    ]
