# Generated by Django 3.1.7 on 2021-03-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210308_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('secret_key', models.CharField(max_length=20, verbose_name='Секретный ключ')),
            ],
            options={
                'verbose_name': 'Ключ регистраций',
                'verbose_name_plural': 'Ключи регистраций',
                'db_table': 'registration_key',
            },
        ),
    ]
