# Generated by Django 3.1.7 on 2021-04-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userpushnotification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpushnotification',
            name='views_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Число просмотров'),
        ),
    ]
