# Generated by Django 3.1.7 on 2021-03-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_registrationkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationkey',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'STUDENT'), (1, 'ADMIN'), (2, 'MODERATOR'), (3, 'SUPER_ADMIN')], default=0, verbose_name='Роль'),
        ),
    ]
