# Generated by Django 3.1.7 on 2021-03-20 10:28

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import virtual_day.utils.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210320_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название сообщения')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Текст сообщения')),
                ('image', models.ImageField(blank=True, null=True, upload_to=virtual_day.utils.image_utils.image_push_notification_path, verbose_name='Фото сообщения')),
                ('user_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None, verbose_name='ID-шники пользователей')),
                ('response', models.JSONField(blank=True, default=None, max_length=1000, null=True, verbose_name='Ответ')),
                ('date_publication', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время отправки')),
                ('is_sent', models.BooleanField(blank=True, default=False, null=True, verbose_name='Отправлен')),
                ('users_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Число пользователей')),
                ('data', models.JSONField(blank=True, default=None, max_length=1000, null=True, verbose_name='Данные уведомления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомления',
                'db_table': 'user_push_template',
            },
        ),
    ]
