""" APPS RETURNING CODES """
OK = 'OK'
BAD_REQUEST = 'bad request'
NOT_FOUND = 'not found'
VALIDATION_ERROR = 'validation error'
AUTH_ERROR = 'authorization error'
ALREADY_EXISTS = 'object already exists'
DOESNT_EXIST = 'object does not exists'
UPLOAD_ERROR = 'file upload error'
PRECONDITION_FAILED = 'PRECONDITION_FAILED'
FORBIDDEN = 'FORBIDDEN'
