# Generated by Django 3.1.7 on 2021-06-01 17:35

from django.db import migrations, models
import django.db.models.deletion
import virtual_day.utils.image_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок билборда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст билборда')),
                ('image', models.ImageField(blank=True, null=True, upload_to=virtual_day.utils.image_utils.billboard_image_path, verbose_name='Фото')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'VIDEO'), (1, 'PDF')], default=1, verbose_name='Тип билборда')),
                ('enable', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_static', models.BooleanField(default=True, verbose_name='Статичный')),
                ('unique_key', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Информационные системы'), (2, 'Логистика'), (3, 'Энергетика'), (4, 'Финансы'), (5, 'Маркетинг'), (6, 'Менеджмент'), (7, 'Международные отношения')], null=True, verbose_name='ключ')),
            ],
            options={
                'verbose_name': 'Билборд',
                'verbose_name_plural': 'Билборды',
                'db_table': 'billboard',
            },
        ),
        migrations.CreateModel(
            name='DodDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('day_date', models.DateField(verbose_name='Дата дня')),
                ('enable', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'День ДОДа',
                'verbose_name_plural': 'Дни ДОДа',
                'db_table': 'dod_day',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('period_start', models.TimeField(verbose_name='Время начала показа')),
                ('period_end', models.TimeField(verbose_name='Время конца показа')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название события')),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Лекция'), (1, 'Билборд')], verbose_name='Тип события')),
                ('enable', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='MediaBillboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=virtual_day.utils.image_utils.pdf_file_image_path, verbose_name='Презентация')),
                ('url_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('kk', 'Kazakh'), ('de', 'German')], max_length=2, verbose_name='язык перевода')),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billboard_statics', to='core.billboard', verbose_name='Билборд')),
            ],
            options={
                'verbose_name': 'Статика билборда',
                'verbose_name_plural': 'Статика билбордов',
                'db_table': 'media_billboard',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('class_room', models.PositiveSmallIntegerField(choices=[(0, 'Аудитория 1'), (1, 'Аудитория 2'), (2, 'Аудитория 3'), (3, 'Аудитория 4'), (4, 'Аудитория 5'), (5, 'Аудитория 6'), (6, 'Аудитория 7')], verbose_name='Дата дня')),
                ('enable', models.BooleanField(default=True, verbose_name='Активен')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lecture', to='core.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
                'db_table': 'lecture',
            },
        ),
    ]
