# Generated by Django 3.1.7 on 2021-03-03 20:42

from django.db import migrations, models
import virtual_day.utils.image_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок билборда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст билборда')),
                ('url_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, null=True, upload_to=virtual_day.utils.image_utils.billboard_image_path, verbose_name='Фото')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1)], default=1, verbose_name='Тип билборда')),
                ('enable', models.BooleanField(default=True, verbose_name='Активен')),
                ('period_start', models.TimeField(verbose_name='Время начала показа')),
                ('period_end', models.TimeField(verbose_name='Время конца показа')),
            ],
            options={
                'verbose_name': 'Билборд',
                'verbose_name_plural': 'Билборды',
                'db_table': 'billboard',
            },
        ),
    ]
