# Generated by Django 3.1.7 on 2021-03-06 17:32

from django.db import migrations, models
import django.db.models.deletion
import virtual_day.utils.image_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок билборда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст билборда')),
                ('url_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, null=True, upload_to=virtual_day.utils.image_utils.billboard_image_path, verbose_name='Фото')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'VIDEO'), (1, 'TEXT')], default=1, verbose_name='Тип билборда')),
                ('enable', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_static', models.BooleanField(default=True, verbose_name='Статичный')),
                ('unique_key', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Информационные системы'), (2, 'Логистика'), (3, 'Энергетика'), (4, 'Финансы'), (5, 'Маркетинг'), (6, 'Менеджмент'), (7, 'Международные отношения')], null=True, verbose_name='ключ')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=virtual_day.utils.image_utils.pdf_file_image_path, verbose_name='Презентация')),
            ],
            options={
                'verbose_name': 'Билборд',
                'verbose_name_plural': 'Билборды',
                'db_table': 'billboard',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('period_start', models.PositiveIntegerField(verbose_name='Время начала показа')),
                ('period_end', models.PositiveIntegerField(verbose_name='Время конца показа')),
                ('event', models.CharField(max_length=255, verbose_name='Событие')),
                ('speaker_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID спикера')),
                ('billboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.billboard', verbose_name='Билборд')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'db_table': 'schedule',
            },
        ),
    ]
