# Generated by Django 3.1.7 on 2021-03-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210307_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='event',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Событие'),
        ),
    ]
