# Generated by Django 3.1.7 on 2021-04-04 19:52

from django.db import migrations, models
import django.db.models.deletion
import virtual_day.utils.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210404_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticBillboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=virtual_day.utils.image_utils.pdf_file_image_path, verbose_name='Презентация')),
                ('url_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('kk', 'Kazakh'), ('de', 'German')], max_length=2, verbose_name='язык перевода')),
            ],
            options={
                'verbose_name': 'Билборд',
                'verbose_name_plural': 'Билборды',
                'db_table': 'static_billboard',
            },
        ),
        migrations.RemoveField(
            model_name='billboard',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='billboard',
            name='url_link',
        ),
        migrations.DeleteModel(
            name='PDFForBillboard',
        ),
        migrations.DeleteModel(
            name='URLForBillboard',
        ),
        migrations.AddField(
            model_name='staticbillboard',
            name='billboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billboard_statics', to='core.billboard', verbose_name='Билборд'),
        ),
    ]
