# Generated by Django 3.1.7 on 2021-04-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210411_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodday',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='event',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'VIDEO'), (1, 'PDF')], default=1, verbose_name='Тип билборда'),
        ),
    ]
